{
	"id": 11907358,
	"name": "High Number of Failed Tasks on Ray.io Node",
	"type": "query alert",
	"query": "avg(last_5m):avg:ray.scheduler.failed_worker_startup{*} by {reason,nodeaddress} > 25",
	"message": "{{#is_alert}}\nThere are {{value}} tasks that failed to be schedule because workers were not available. This occurred on node: {{nodeaddress.name}}. The stated reason was {{reason.name}}.\n{{/is_alert}}",
	"tags": [],
	"options": {
		"thresholds": {
			"critical": 25
		},
		"notify_audit": false,
		"include_tags": true,
		"new_group_delay": 60,
		"renotify_interval": 0,
		"escalation_message": "",
		"notify_no_data": false,
		"avalanche_window": 10,
		"silenced": {}
	},
	"priority": null,
	"restricted_roles": null
}