name: Submit traces

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  submit:
    name: Submit traces
    runs-on: ubuntu-22.04

    services:
      dd-agent:
        image: gcr.io/datadoghq/agent:latest
        ports:
        - "8126:8126"
        env:
          DD_API_KEY: "${{ secrets.DD_API_KEY }}"
          DD_HOSTNAME: "none"
          DD_INSIDE_CI: "true"
          DD_LOG_LEVEL: "warn"

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      id: download
      with:
        # With the 'pattern' setting and no files to download (for example, ddev tests don't produce traces)
        # this action will succeed BUT NOT CREATE 'path'.
        # Subsequent actions must check that 'path' exists to avoid failing.
        pattern: "traces-*"
        path: captured-traces
        merge-multiple: true

    - name: Replay
      if: ${{ hashFiles('captured-traces') != '' }}
      run: |-
        cd captured-traces
        for request in *; do
          echo "/// Replaying: $request"
          python ../.ddev/ci/scripts/traces.py replay --record-file "$request"
        done

    - name: Show Agent status
      if: ${{ hashFiles('captured-traces') != '' }}
      run: docker exec $(docker ps --format "{{.ID}}") agent status

    - uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
      if: steps.download.outcome == 'success'
      with:
        name: "${{ inputs.artifact-name }}"
        failOnError: false
